export const DATA = [
    {
        cause: "Погода плохая была!",
        company: "Кыргызстан",
        description: "НфывдлфывфджаьмЖДФЫОАждфыаьжДФАЬждЬАЖДЬАЖДьфыаЖ...",
        economic: "Продажа героина",
        id: 1,
        name: "Вася",
        organ: "Полиция",
        region: "Чолпон-Ата",
        status: "В обработке",
        subjects: "Физическое лицо",
    },
    {
        cause: "Коррупция",
        company: "Кыргызстан",
        description: "saf[psdokfaksf;lasfdk:ASDLGPO",
        economic: "Продажа местных семичек",
        id: 2,
        inn: 112131354124,
        organ: "Полиция",
        region: "Бишкек",
        status: "Одобрено",
        subjects: "Юридическое лицо",

    },
    {
        cause: "Распространение слухов",
        company: "Кыргызстан",
        description: "asdmasf;lkGEDAL:LF;LAFD;lAKFSAasflasfd",
        economic: "Продажа бамбука",
        id: 3,
        name: "Pety",
        organ: "Врач",
        region: "Чолпон-Ата",
        status: "На рассмотрений",
        subjects: "физическое лицо",

    },
    {
        cause: "Распространение слухов",
        company: "Кыргызстан",
        description: "fa;lsmfmA:LSFMASL:mASDMLALSMDmld:SA",
        economic: "Распространение бланков",
        id: 4,
        name: "Pety",
        organ: "Врач",
        region: "Каракол",
        status: "Отказ",
        subjects: "физическое лицо",
    },
    {
        cause: "Конкуренция",
        company: "Россия",
        description: "asd;lasmdlaMSFL:MSDA:laSDdas:ASD<LSADLlsl;sdamldas",
        economic: "Аренда кофешек",
        id: 5,
        inn: 213123213,
        organ: "Врач",
        region: "Каракол",
        status: "Одобрено",
        subjects: "юридическое лицо",
    },
    {
        cause: "Нарушение какой то статьи",
        company: "Россия",
        description: "asdpkasdl;al;sdk;lASKDl;ASKDl;asdkasdlkadslsk;l...",
        economic: "Аренда кофешек",
        id: 6,
        name: "Саша",
        organ: "Врач",
        region: "Каракол",
        status: "Одобрено",
        subjects: "физическое лицо",

    },
    {
        cause: "Погода плохая была!",
        company: "Кыргызстан",
        description: "НфывдлфывфджаьмЖДФЫОАждфыаьжДФАЬждЬАЖДЬАЖДьфыаЖ...",
        economic: "Продажа местных семичек",
        id: 7,
        name: "Георгий",
        organ: "Полиция",
        region: "Чолпон-Ата",
        status: "На рассмотрений",
        subjects: "Физическое лицо",
    },
    {
        cause: "Воровство",
        company: "Кыргызстан",
        description: "saf[psdokfaksf;lasfdk:ASDLGPO",
        economic: "Продажа африканской соли",
        id: 8,
        inn: 112131354124,
        organ: "Полиция",
        region: "Бишкек",
        status: "На рассмотрений",
        subjects: "Юридическое лицо",

    },
];